[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# remappings = [
#     "contracts/=Users/atharvamuley/repos/cyfrin-frontend/coffee-html-ts/contracts/",
# ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
